### ISSUE TITLE
Just here to say ....

### ISSUE THREAD

**Issue by aidanheerdegen** [converged-computing/metrics-operator#49]
Love the logo!

**Comment by vsoch** [comment]
Thank you! It was a collaboration between an AI image generator and I - I have a small GPU I run in my apartment for these purposes, mostly to make hilarious pictures of Jeff Bezos riding dinosaurs (but sometimes something useful)? This guy was a few variations, and then I brought him into Gimp for a lot of manual editing - the trick to making them look good is cleaning up all the edges, fixing some of the weird parts with custom painting, and basically doing that until you are satisfied. I use other programs / online tools to create the text. I think he came out adorable! 

And I'm heavily working on the operator itself - I have two designs in today for ensuring 1:1 mapping of pods to nodes (without requiring a resource limit/request) and I'm waiting to hear some feedback on the best approach.
